version: '2'
services:
  o365-smtp-relay:
    image: antlac1/docker-o365-smtp-relay:latest
    environment:
      SYSTEM_TIMEZONE: "America/New_York"
      MYNETWORKS: "10.0.0.0/8 192.168.0.0/16 172.0.0.0/8"
      EMAIL: "hello@beautif.ul"
      EMAILPASS: "abcd1234"
    ports:
      - "9025:25" 
